- name: Setup EC2
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Create file /tmp/test_file.txt with content "It works"
      copy:
        dest: /tmp/test_file.txt
        content: "It works!\n"

- name: Deploy Apache Tomcat on Ubuntu for your java web applications
  hosts: localhost
  gather_facts: yes
  become: true
  
  tasks: 
    - name: Installing OpenJDK 8 to the host(s)
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present

    - name: Deleting content & directory
      file:
        state: absent
        path: /tmp/tomcat

    - name: Creating /tmp/tomcat directory
      file:
        path: /tmp/tomcat
        state: directory
        mode: 0755

    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.tar.gz
        dest: /tmp/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Create systemd service file for Tomcat
      copy:
        dest: /tmp/tomcat/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target
          
          [Service]
          Type=forking
          
          Environment=JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          Environment=CATALINA_PID=/tmp/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/tmp/tomcat
          Environment=CATALINA_BASE=/tmp/tomcat
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
          
          ExecStart=/tmp/apache-tomcat-9.0.107/bin/startup.sh
          ExecStop=/tmp/apache-tomcat-9.0.107/bin/shutdown.sh
          
          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
        
    - name: Adding tomcat group
      group:
        name: tomcat
        
    - name: Adding tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no
        
    - name: Changing ownership
      file:
        path: /tmp/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
        
    - name: Copying Tomcat service file from local to remote
      copy:
         src: /tmp/tomcat/tomcat.service
         dest: /etc/systemd/system/
         mode: 0755
         
    - name: Starting and enabling Tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: true
        daemon_reload: true