- name: Setup EC2
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Create file /tmp/test_file.txt with content "It works"
      copy:
        dest: /tmp/test_file.txt
        content: "It works!\n"

- name: Install Tomcat
  hosts: tomcat_servers
  become: yes
  
  tasks: 
    - name: Install Java
      yum: 
        name: java-1.8.0-openjdk
        state: present
    
    - name: Download Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-9/v9.0.34/bin/apache-tomcat-9.0.34.tar.gz
        dest: /opt/

    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.34.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Start Tomcat Service
      service:
        name: tomcat
        state: started
        enabled: yes