- name: Setup EC2
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Create file /tmp/test_file.txt with content "It works"
      copy:
        dest: /tmp/test_file.txt
        content: "It works!\n"

- name: Deploy Apache Tomcat on Ubuntu for your java web applications
  hosts: medium
  gather_facts: yes
  become: true
  
  tasks:
    - name: Installing OpenJDK 8 to the host(s)
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
        
    - name: Deleting content & directory
      file:
        state: absent
        path: /opt/Tomcat
        
    - name: Creating /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        
    - name: Downloading & unarchiving
      unarchive:
        src: "{{ tomcat_archive_url }}"
        dest: /opt/tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
        
    - name: Adding tomcat group
      group:
        name: tomcat
        
    - name: Adding tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no
    
    - name: Changing ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
        
    - name: Copying Tomcat service file from local to remote
      copy:
         src: files/tomcat.service
         dest: /etc/systemd/system/
         mode: 0755
    
    - name: Starting and enabling Tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: true
        daemon_reload: true