- name: Setup EC2
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Create file /tmp/test_file.txt with content "It works"
      copy:
        dest: /tmp/test_file.txt
        content: "It works!\n"

- name: Deploy Apache Tomcat on Ubuntu for your java web applications
  hosts: localhost
  become: true
  
  tasks:     
    - name: Creating /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755
        
    - name: Install Java (Tomcat dependency)
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.tar.gz
        dest: /tmp/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /opt/
        remote_src: yes
        
    - name: Adding tomcat group
      group:
        name: tomcat
        
    - name: Adding tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /user/share/tomcat
        createhome: no
        
    - name: Changing ownership
      file:
        path: /opt/tomcat
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
        
    - name: Create systemd service file for Tomcat
      copy:
        dest: /etc/systemd/system/{{ tomcat_service }}.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_group }}

          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
          Environment="CATALINA_PID={{ install_dir }}/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ install_dir }}"
          Environment="CATALINA_BASE={{ install_dir }}"
          Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"

          ExecStart={{ install_dir }}/bin/startup.sh
          ExecStop={{ install_dir }}/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable Tomcat service
      systemd:
        name: "{{ tomcat_service }}"
        enabled: yes

    - name: Start Tomcat service
      systemd:
        name: "{{ tomcat_service }}"
        state: started