
- name: Ensure Apache is installed
  apt:
    name: apache2
    state: present
    update_cache: true

- name: Enable required Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http

- name: Deploy updated Apache default site config
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - Reload Apache

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true