
- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: true

- name: Enable required Apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - proxy
    - proxy_http

- name: Deploy updated Apache default site config
  template:
    src: 000-default.conf.j2
    dest: "{{ apache_conf_path }}"
  notify: Reload Apache

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true