- name: copy the war file to tomcat
  copy:
    src: /opt/app/visitor_counter_app/target/visitor-counter-1.0-SNAPSHOT.war
    dest: /opt/tomcat/apache-tomcat-9.0.107/webapps/visitor-counter.war
    owner: tomcat
    group: tomcat
    mode: '0644'

- name: Restart Tomcat
  service:
    name: tomcat
    state: restarted