---
- name: Setup EC2
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Create file /tmp/test_file.txt with content "It works"
      copy:
        dest: /tmp/test_file.txt
        content: "It works!\n"

- name: Deploy Apache Tomcat on Ubuntu for your java web applications
  hosts: localhost
  gather_facts: yes
  become: true
  
  tasks: 
    - name: Installing OpenJDK 8 to the host(s)
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present

    - name: Deleting content & directory
      file:
        state: absent
        path: /opt/tomcat

    - name: Creating /opt/tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        mode: 0755

    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.107/bin/apache-tomcat-9.0.107.tar.gz
        dest: /tmp/apache-tomcat.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: Create systemd service file for Tomcat
      copy:
        dest: /opt/tomcat/tomcat.service
        content: |
          - name: Create systemd service file for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat Web Application Container
          After=network.target

          [Service]
          Type=forking

          Environment=JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          Environment=CATALINA_PID=/opt/tomcat/temp/tomcat.pid
          Environment=CATALINA_HOME=/opt/tomcat/apache-tomcat-9.0.107
          Environment=CATALINA_BASE=/opt/tomcat/apache-tomcat-9.0.107
          Environment='CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC'
          Environment='JAVA_OPTS=-Djava.awt.headless=true -Djava.security.egd=file:/dev/./urandom'
          ExecStart=/opt/tomcat/apache-tomcat-9.0.107/bin/startup.sh
          ExecStop=/opt/tomcat/apache-tomcat-9.0.107/bin/shutdown.sh

          User=tomcat
          Group=tomcat
          UMask=0007
          RestartSec=10
          Restart=always

          [Install]
          WantedBy=multi-user.target
        
    - name: Adding tomcat group
      group:
        name: tomcat
        
    - name: Adding tomcat user
      user:
        name: tomcat
        group: tomcat
        shell: /bin/false
        create_home: no

    - name: Changing ownership
      file:
        path: /opt/tomcat/apache-tomcat-9.0.107
        owner: tomcat
        group: tomcat
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
         
    - name: Starting and enabling Tomcat service
      systemd:
        name: tomcat
        state: restarted
        enabled: true
        daemon_reload: true

- name: Deploy WAR file to Tomcat
  hosts: all
  become: true
  tasks:
    - name: copy the war file to tomcat
      copy:
        src: /tmp/build/Terraform-ansible-aws/visitor_counter_app/target/visitor-counter-1.0-SNAPSHOT.war
        dest: /opt/tomcat/apache-tomcat-9.0.107/webapps/visitor-counter.war
        owner: tomcat
        group: tomcat
        mode: '0644'

    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted

- name: Setup Apache reverse proxy for visitor-counter
  hosts: localhost
  become: true

  vars:
    proxy_path: /visitor-counter

  tasks:
    - name: Ensure Apache is installed
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Enable required Apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - proxy
        - proxy_http

    - name: Deploy updated Apache default site config
      template:
        src: 000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf
      notify:
        - Reload Apache

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: true

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded