#cloud-config

package_update: true
packages:
  - unzip
  - ansible
  - awscli

write_files:
  - path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    content: |
      {
        "agent": {
          "metrics_collection_interval": 60,
          "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
          "run_as_user": "root"
        },
        "logs": {
          "logs_collected": {
            "files": {
              "collect_list": [
                {
                  "file_path": "/var/log/syslog",
                  "log_group_name": "/ec2/devops-project",
                  "log_stream_name": "{instance_id}/syslog",
                  "timestamp_format": "%b %d %H:%M:%S"
                },
                {
                  "file_path": "/var/log/cloud-init.log",
                  "log_group_name": "/ec2/devops-project",
                  "log_stream_name": "{instance_id}/cloud-init"
                }
              ]
            }
          }
        },
        "metrics": {
          "append_dimensions": {
            "InstanceId": "{instance_id}"
          },
          "metrics_collected": {
            "cpu": {
              "measurement": ["cpu_usage_idle", "cpu_usage_user", "cpu_usage_system"],
              "metrics_collection_interval": 60,
              "totalcpu": true
            },
            "mem": {
              "measurement": ["mem_used_percent"],
              "metrics_collection_interval": 60
            },
            "disk": {
              "measurement": ["disk_used_percent"],
              "metrics_collection_interval": 60,
              "resources": ["*"]
            }
          }
        }
      }

runcmd:
  - curl -O https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
  - dpkg -i -E ./amazon-cloudwatch-agent.deb

  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a stop || true
  - /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a start -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json -m ec2 || echo "CW Agent start failed"

  - aws s3 cp s3://abz-devops-project-1702/app.zip /tmp/visitor_counter_app.zip --region eu-west-2
  - aws s3 cp s3://abz-devops-project-1702/ansible.zip /tmp/ansible.zip --region eu-west-2

  - unzip /tmp/visitor_counter_app.zip -d /opt
  - unzip /tmp/ansible.zip -d /opt

  - cd /opt/ansible && ansible-playbook playbook.yml -i localhost, --connection=local